### ISSUE TITLE
Update `PKGBUILD` for `manjaro-gdm-theme`

### ISSUE THREAD

**Issue by bryango** [Ste74/manjaro-gnome-theme#1]
The `PKGBUILD` linked in `README.md` seems to be outdated, and I can't find the `PKGBUILD` for `manjaro-gdm-theme` anywhere. Could you please update / provide the latest `PKGBUILD` file? I would like to tweak the lock screen background :stuck_out_tongue_winking_eye:

**Comment by Ste74** [comment]
Hi, thank you, you are right; forgot to update the **readme**. Well done with this 026a0131a988f9cc96d0c9854595da6a59dc652d

**Comment by bryango** [comment]
Thank you! But still, the new link <https://gitlab.manjaro.org/packages/community/gnome/manjaro-gdm-theme> points to a 404 page (at least for me, a logged in but non-admin user), it seems that the `PKGBUILD` is not published / pushed to gitlab. 

I have searched gitlab before, and there is no `PKGBUILD` for this package. I tried `buildtree -s` from `manjaro-tools`,  and it seems to be pulling the old github (not the new gitlab) repo as well. Should I open an issue there at gitlab? :stuck_out_tongue_closed_eyes:

**Comment by Ste74** [comment]
Opss.. you are right i forgot to publish pubblic ... Gitlab work in a different way like github.. we have to mark pubblic any repository we creating and i fortgot this :smile: .. try now is pubblic.. for buildtree thank you i will do the corrections

**Comment by bryango** [comment]
Thank you soooo much! Gitlab certainly needs a bit getting used to. :smirk: I guess I will close this now!
